---
title: "Simulate Survey Data"
author: "Alison Rector"
date: "2022-09-21"
output:
  word_document: default
  pdf_document: default
subtitle: 5 Questions, 2 Timepoints
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("flextable")
#install.packages("table1")
library(flextable)
library(table1)
library(dplyr)
```

```{r}

# Create a list of survey responses
Survey_Responses_T1<-c("Strongly Agree", "Agree", "Disagree", "Disagree", "Strongly Disagree", "Do Not Have", " ")

# Randomly sample from this list for 5 questions to create Time 1 dataset
set.seed(576)
SimulatedSurvey_T1 <- data.frame(Q1=sample(Survey_Responses_T1, 100, replace=TRUE),
                                 Q2=sample(Survey_Responses_T1, 100, replace=TRUE),
                                 Q3=sample(Survey_Responses_T1, 100, replace=TRUE),
                                 Q4=sample(Survey_Responses_T1, 100, replace=TRUE),
                                 Q5=sample(Survey_Responses_T1, 100, replace=TRUE))

saveRDS(SimulatedSurvey_T1, "./Simulated_5Q_T1.rds")

# Create a list of survey responses
Survey_Responses_T2<-c("Strongly Agree", "Agree", "Strongly Agree", "Agree","Disagree",  "Strongly Disagree", "Do Not Have", " ")
# Randomly sample from this list for 5 questions to create Time 2 dataset
set.seed(726)
SimulatedSurvey_T2 <- data.frame(Q1=sample(Survey_Responses_T2, 100, replace=TRUE),
                                 Q2=sample(Survey_Responses_T2, 100, replace=TRUE),
                                 Q3=sample(Survey_Responses_T2, 100, replace=TRUE),
                                 Q4=sample(Survey_Responses_T2, 100, replace=TRUE),
                                 Q5=sample(Survey_Responses_T2, 100, replace=TRUE))

saveRDS(SimulatedSurvey_T2, "./Simulated_5Q_T2.rds")

```

```{r}
combined_data <- bind_rows(list(SimulatedSurvey_T1, SimulatedSurvey_T2), .id = "timepoint")
first_table <- table1(~Q1+Q2+Q3+Q4+Q5|timepoint, data = combined_data, output="latex")
t1flex(first_table) %>%
  padding(padding = 0, part = "all") %>% 
  valign(valign="top", part="header")%>%
  autofit()%>% 
  fit_to_width(7)%>%
  fontsize(size=10, part="header")%>%
  fontsize(size=10)%>%
  add_header_lines("Summary of Survey Results by Timepoint")
```

